# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import schedule_crawler.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleinfo',
            name='dateEnd',
            field=models.DateField(validators=[schedule_crawler.models.dateEndValidator]),
        ),
        migrations.AlterField(
            model_name='scheduleinfo',
            name='dateStart',
            field=models.DateField(validators=[schedule_crawler.models.dateStartValidator]),
        ),
    ]
