# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_crawler', '0002_auto_20180222_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleinfo',
            name='description',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
