# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_crawler', '0003_scheduleinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleinfo',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
