# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import schedule_crawler.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_crawler', '0004_auto_20180222_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleinfo',
            name='description',
        ),
        migrations.AlterField(
            model_name='scheduleinfo',
            name='dateEnd',
            field=models.DateTimeField(validators=[schedule_crawler.models.dateEndValidator]),
        ),
        migrations.AlterField(
            model_name='scheduleinfo',
            name='dateStart',
            field=models.DateTimeField(validators=[schedule_crawler.models.dateStartValidator]),
        ),
    ]
