# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notice',
            field=models.BooleanField(default=True),
        ),
    ]
