# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_config', '0002_client_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='notice',
            new_name='alarm_active',
        ),
    ]
